version: '3'

services:
  platformer-game:
    container_name: platformer-game
    build: .
    volumes:
      - ./src:/app/src
    environment:
      - DISPLAY=host.docker.internal:0
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: 'no'
